import { useEffect, useRef, useState } from 'react';
import './ResearchProgress.css';

const INITIAL_STEPS = [
  {
    id: 1,
    label: 'Structuring your business profile',
    detail: 'Business profile structured from interview answers',
  },
  {
    id: 2,
    label: 'Searching knowledge base — 5 documents',
    detail: '5 relevant knowledge base documents retrieved',
  },
  {
    id: 3,
    label: 'Running live web research — 3 results found',
    detail: '3 live web sources analysed',
  },
  {
    id: 4,
    label: 'Analysing 6 business dimensions',
    detail: '6 dimension scores computed with evidence',
  },
  {
    id: 5,
    label: "Running devil's advocate analysis",
    detail: 'Counter-arguments generated by Mistral 7B',
  },
];

function getStepStates(activeIndex) {
  return INITIAL_STEPS.map((step, index) => ({
    ...step,
    state: index < activeIndex ? 'done' : index === activeIndex ? 'active' : 'pending',
  }));
}

function ResearchProgress({ onResearchComplete }) {
  const [steps, setSteps] = useState(() => getStepStates(0));
  const onCompleteRef = useRef(onResearchComplete);

  useEffect(() => {
    onCompleteRef.current = onResearchComplete;
  }, [onResearchComplete]);

  useEffect(() => {
    let activeIndex = 0;

    const interval = setInterval(() => {
      if (activeIndex >= INITIAL_STEPS.length - 1) {
        clearInterval(interval);
        setSteps(
          INITIAL_STEPS.map((step) => ({
            ...step,
            state: 'done',
          })),
        );
        setTimeout(() => {
          onCompleteRef.current();
        }, 500);
        return;
      }

      activeIndex += 1;
      setSteps(getStepStates(activeIndex));
    }, 1200);

    return () => clearInterval(interval);
  }, []);

  return (
    <div className="research-progress">
      <h2 className="research-progress-heading">Researching your idea...</h2>
      {steps.map((step) => (
        <div
          key={step.id}
          className={`research-step research-step--${step.state}`}
        >
          <div className={`research-step-icon research-step-icon--${step.state}`}>
            {step.state === 'done' ? '✓' : ''}
          </div>
          <div>
            <div className="research-step-label">{step.label}</div>
            {step.state === 'done' && (
              <div className="research-step-detail">{step.detail}</div>
            )}
          </div>
        </div>
      ))}
    </div>
  );
}

export default ResearchProgress;
